[package]
name = "leancache"
version = "0.1"
lean_version = "nightly-2018-11-13"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "51f95e4e37a4e6742afbd19fbb6008995dee4c2f"}
