[package]
name = "leancache"
version = "0.1"
lean_version = "khoek/klean:3.4.7"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "f529870e34eb5370ae8ac1f49f728547e4f6bbe5"}
